In [60]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [61]:
'''

'''

'\n\n'

In [62]:
dframe_wine = pd.read_csv('winequality-red.csv',sep=';')
dframe_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [63]:
# what if we want to know the highest alcohol content wine for each quality range. We can find out using split,
# apply, combine procedure
# create function that assigns a rank for alcohol content. 1 is the highest rank
def ranker(df):
    df['alc_content_rank'] = np.arange(len(df)) + 1
    return df

In [64]:
# sort df by alcohol in ascending order
dframe_wine.sort_values(by='alcohol', ascending=False, inplace=True)
dframe_wine.head()
dframe_wine.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1599 entries, 652 to 517
Data columns (total 12 columns):
fixed acidity           1599 non-null float64
volatile acidity        1599 non-null float64
citric acid             1599 non-null float64
residual sugar          1599 non-null float64
chlorides               1599 non-null float64
free sulfur dioxide     1599 non-null float64
total sulfur dioxide    1599 non-null float64
density                 1599 non-null float64
pH                      1599 non-null float64
sulphates               1599 non-null float64
alcohol                 1599 non-null float64
quality                 1599 non-null int64
dtypes: float64(11), int64(1)
memory usage: 162.4 KB

In [66]:
dframe_grp = dframe_wine.groupby('quality')
dframe_grp.mean()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
3,8.360000,0.884500,0.171000,2.635000,0.122500,11.000000,24.900000,0.997464,3.398000,0.570000,9.955000
4,7.779245,0.693962,0.174151,2.694340,0.090679,12.264151,36.245283,0.996542,3.381509,0.596415,10.265094
5,8.167254,0.577041,0.243686,2.528855,0.092736,16.983847,56.513950,0.997104,3.304949,0.620969,9.899706
6,8.347179,0.497484,0.273824,2.477194,0.084956,15.711599,40.869906,0.996615,3.318072,0.675329,10.629519
7,8.872362,0.403920,0.375176,2.720603,0.076588,14.045226,35.020101,0.996104,3.290754,0.741256,11.465913
8,8.566667,0.423333,0.391111,2.577778,0.068444,13.277778,33.444444,0.995212,3.267222,0.767778,12.094444

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
652,15.9,0.360,0.65,7.50,0.096,22.0,71.0,0.99760,2.98,0.84,14.900000,5,1
588,5.0,0.420,0.24,2.00,0.060,19.0,50.0,0.99170,3.72,0.74,14.000000,8,1
142,5.2,0.340,0.00,1.80,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,1
144,5.2,0.340,0.00,1.80,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,2
1270,5.0,0.380,0.01,1.60,0.048,26.0,60.0,0.99084,3.70,0.75,14.000000,6,3
1269,5.5,0.490,0.03,1.80,0.044,28.0,87.0,0.99080,3.50,0.82,14.000000,8,2
467,8.8,0.460,0.45,2.60,0.065,7.0,18.0,0.99470,3.32,0.79,14.000000,6,4
821,4.9,0.420,0.00,2.10,0.048,16.0,42.0,0.99154,3.71,0.74,14.000000,7,1
1114,5.0,0.400,0.50,4.30,0.046,29.0,80.0,0.99020,3.49,0.66,13.600000,6,5
1228,5.1,0.420,0.00,1.80,0.044,18.0,88.0,0.99157,3.68,0.73,13.600000,7,2
1132,7.4,0.360,0.34,1.80,0.075,18.0,38.0,0.99330,3.38,0.88,13.600000,7,3
1477,5.3,0.470,0.11,2.20,0.048,16.0,89.0,0.99182,3.54,0.88,13.600000,7,4
1475,5.3,0.470,0.11,2.20,0.048,16.0,89.0,0.99182,3.54,0.88,13.566667,7,5
455,11.3,0.620,0.67,5.20,0.086,6.0,19.0,0.99880,3.22,0.69,13.400000,8,3
45,4.6,0.520,0.15,2.10,0.054,8.0,65.0,0.99340,3.90,0.56,13.100000,4,1
1120,7.9,0.540,0.34,2.50,0.076,8.0,17.0,0.99235,3.20,0.72,13.100000,8,4
353,13.5,0.530,0.79,4.80,0.120,23.0,77.0,1.00180,3.18,0.77,13.000000,5,2
1287,8.0,0.600,0.08,2.60,0.056,3.0,7.0,0.99286,3.22,0.37,13.000000,5,3
132,5.6,0.500,0.09,2.30,0.049,17.0,99.0,0.99370,3.63,0.63,13.000000,5,4
131,5.6,0.500,0.09,2.30,0.049,17.0,99.0,0.99370,3.63,0.63,13.000000,5,5
390,5.6,0.850,0.05,1.40,0.045,12.0,88.0,0.99240,3.56,0.82,12.900000,8,5
1276,8.5,0.400,0.40,6.30,0.050,3.0,10.0,0.99566,3.28,0.56,12.000000,4,2
1239,6.5,0.670,0.00,4.30,0.057,11.0,20.0,0.99488,3.45,0.56,11.800000,4,3
1124,6.5,0.580,0.00,2.20,0.096,3.0,13.0,0.99557,3.62,0.62,11.500000,4,4
1235,6.0,0.330,0.32,12.90,0.054,6.0,113.0,0.99572,3.30,0.56,11.500000,4,5
899,8.3,1.020,0.02,3.40,0.084,6.0,11.0,0.99892,3.48,0.49,11.000000,3,1
1299,7.6,1.580,0.00,2.10,0.137,5.0,9.0,0.99476,3.50,0.40,10.900000,3,2
690,7.4,1.185,0.00,4.25,0.097,5.0,14.0,0.99660,3.63,0.54,10.700000,3,3
1478,7.1,0.875,0.05,5.70,0.082,3.0,14.0,0.99808,3.40,0.52,10.200000,3,4
1505,6.7,0.760,0.02,1.80,0.078,6.0,12.0,0.99600,3.55,0.63,9.950000,3,5

In [9]:
# now find highest alc content for each ranking
num_of_qual = dframe_wine['quality'].value_counts()
num_of_qual

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [12]:
dframe_wine[dframe_wine.alc_content_rank == 1].head(len(num_of_qual))

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
652,15.9,0.36,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.9,5,1
588,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8,1
142,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,1
821,4.9,0.42,0.00,2.1,0.048,16.0,42.0,0.99154,3.71,0.74,14.0,7,1
45,4.6,0.52,0.15,2.1,0.054,8.0,65.0,0.99340,3.90,0.56,13.1,4,1
899,8.3,1.02,0.02,3.4,0.084,6.0,11.0,0.99892,3.48,0.49,11.0,3,1